"""
HAL File Generator
==================
Generates LinuxCNC HAL files from MachineConfig.
"""

from __future__ import annotations
import os
from config.machine_config import MachineConfig


class HALGenerator:
    def __init__(self, cfg: MachineConfig):
        self.cfg = cfg

    def generate_machine_hal(self) -> str:
        """Generate the main machine.hal content."""
        c = self.cfg
        lines = [
            "# Generated by PNCconf Qt Wizard",
            "# Main HAL file",
            "",
            "# ── Load real-time components ──────────────────────────────",
        ]

        # Motion
        lines.append(f"loadrt [KINS]KINEMATICS")
        lines.append(f"loadrt [EMCMOT]EMCMOT "
                     f"servo_period_nsec=[EMCMOT]SERVO_PERIOD "
                     f"num_joints={len(c.axis_config)}")
        lines.append("")

        # Mesa driver
        lines.append(f"# Mesa {c.mesa.board_name}")
        lines.append(f"loadrt hm2_eth board_ip=192.168.1.121 config=\"firmware={c.mesa.firmware} num_encoders={c.mesa.num_encoders} num_stepgens={c.mesa.num_stepgens} num_pwmgens=0\"")
        lines.append("")

        # PID components
        if c.realtime.use_pid:
            num_axes = len(c.axis_config)
            lines.append(f"loadrt pid num_chan={num_axes}")
            lines.append("")

        # Optional components
        if c.realtime.use_absolute:
            lines.append("loadrt abs count=1")
        if c.realtime.use_scale:
            lines.append("loadrt scale count=2")
        if c.realtime.use_lowpass:
            lines.append("loadrt lowpass count=1")
        if c.realtime.use_mux2:
            lines.append("loadrt mux2 count=1")
        for comp in c.realtime.custom_components:
            lines.append(f"loadrt {comp}")
        lines.append("")

        # Servo thread functions
        lines.append("# ── Servo thread ────────────────────────────────────────")
        lines.append("addf hm2_[HOSTMOT2](BOARD).read          servo-thread")
        lines.append("addf motion-command-handler              servo-thread")
        lines.append("addf motion-controller                   servo-thread")

        for i, axis in enumerate(c.axis_config):
            if c.realtime.use_pid:
                lines.append(f"addf pid.{i}.do-pid-calcs              servo-thread")

        lines.append("addf hm2_[HOSTMOT2](BOARD).write         servo-thread")
        lines.append("")

        # Net statements per axis
        lines.append("# ── Axis nets ────────────────────────────────────────────")
        for i, ax_letter in enumerate(c.axis_config):
            ax = c.axes.get(ax_letter)
            if ax is None:
                continue
            lines.append(f"")
            lines.append(f"# Joint {i} ({ax_letter})")
            lines.append(f"net j{i}pos-cmd <= joint.{i}.motor-pos-cmd")
            lines.append(f"net j{i}pos-cmd => pid.{i}.command")
            lines.append(f"net j{i}pos-fb  <= hm2_[HOSTMOT2](BOARD).encoder.{i:02d}.position")
            lines.append(f"net j{i}pos-fb  => pid.{i}.feedback")
            lines.append(f"net j{i}pos-fb  => joint.{i}.motor-pos-fb")
            lines.append(f"net j{i}output  <= pid.{i}.output")
            lines.append(f"net j{i}output  => hm2_[HOSTMOT2](BOARD).stepgen.{i:02d}.velocity-cmd")
            lines.append(f"net j{i}enable  <= joint.{i}.amp-enable-out")
            lines.append(f"net j{i}enable  => pid.{i}.enable")

        lines.append("")

        # Spindle
        lines.append("# ── Spindle ──────────────────────────────────────────────")
        lines.append("net spindle-vel-cmd <= spindle.0.speed-out-rps-abs")
        lines.append("net spindle-vel-cmd => hm2_[HOSTMOT2](BOARD).7i76.0.0.spinout")
        lines.append("net spindle-enable  <= spindle.0.on")
        lines.append("net spindle-enable  => hm2_[HOSTMOT2](BOARD).7i76.0.0.spinena")
        lines.append("net spindle-ccw     <= spindle.0.reverse")
        lines.append("net spindle-ccw     => hm2_[HOSTMOT2](BOARD).7i76.0.0.spindir")
        lines.append("")

        # E-stop
        lines.append("# ── E-stop / Enable ─────────────────────────────────────")
        lines.append("net estop-out <= iocontrol.0.user-enable-out")
        lines.append("net estop-out => iocontrol.0.emc-enable-in")
        lines.append("")

        # Custom HAL
        if c.options.custom_hal_before:
            lines.append("# ── Custom HAL (before) ──────────────────────────────")
            lines.append(c.options.custom_hal_before)
        if c.options.custom_hal_after:
            lines.append("# ── Custom HAL (after) ───────────────────────────────")
            lines.append(c.options.custom_hal_after)

        return "\n".join(lines)

    def generate_custom_hal(self) -> str:
        """Generate custom.hal stub."""
        return "\n".join([
            "# custom.hal - Add your custom HAL commands here.",
            "# This file is not overwritten by PNCconf.",
            "",
        ])

    def write_all(self, output_dir: str):
        """Write all HAL files to output_dir."""
        os.makedirs(output_dir, exist_ok=True)
        name = self.cfg.machine_name

        with open(os.path.join(output_dir, f"{name}.hal"), "w") as f:
            f.write(self.generate_machine_hal())

        with open(os.path.join(output_dir, "custom.hal"), "w") as f:
            f.write(self.generate_custom_hal())
