"""
HAL File Generator — Full Feature Parity
=========================================
Generates LinuxCNC HAL files from MachineConfig.

Covers:
  • loadrt for hm2_eth / hm2_pci with full config string
  • setp for stepgen timing parameters
  • net statements derived from connector pin assignments
  • Spindle, E-stop, amp-enable wiring
  • External controls (VFD, MPG, overrides)
  • Custom HAL sections
  • INI file generation
"""

from __future__ import annotations
import os
from typing import List, Dict, Optional, Set

from config.machine_config import (
    MachineConfig, MesaPin,
    STEPGEN_FUNCTIONS, ENCODER_FUNCTIONS, PWMGEN_FUNCTIONS, SSERIAL_FUNCTIONS,
    FUNC_LOOKUP, get_firmware_spec,
)


class HALGenerator:
    def __init__(self, cfg: MachineConfig):
        self.cfg = cfg

    # ─────────────────────────────────────────────────────────────────────────
    # Public entry points
    # ─────────────────────────────────────────────────────────────────────────

    def generate_machine_hal(self) -> str:
        """Generate the main machine.hal file content."""
        c = self.cfg
        m = c.mesa
        board = m.board_name
        lines: List[str] = []

        lines += [
            f"# Generated by PNCconf Qt Wizard",
            f"# Board: {board}  Firmware: {m.firmware}",
            f"# Machine: {c.machine_name}",
            "",
        ]

        # ── loadrt ────────────────────────────────────────────────────────
        lines += ["# ── Load real-time components ──────────────────────────────", ""]

        lines.append("loadrt [KINS]KINEMATICS")
        lines.append(
            f"loadrt [EMCMOT]EMCMOT "
            f"servo_period_nsec=[EMCMOT]SERVO_PERIOD "
            f"num_joints={len(c.axis_config)}"
        )
        lines.append("")

        # Mesa driver — hm2_eth for Ethernet boards, hm2_pci for PCI
        eth_boards = {"7i76e", "7i92", "7i96", "7i96S"}
        driver = "hm2_eth" if board in eth_boards else "hm2_pci"
        config_str = (
            f"firmware={m.firmware} "
            f"num_encoders={m.num_encoders} "
            f"num_stepgens={m.num_stepgens} "
            f"num_pwmgens={m.num_pwmgens}"
        )
        if driver == "hm2_eth":
            board_ip = getattr(m, "ip_address", "192.168.1.121") or "192.168.1.121"
            lines.append(
                f"loadrt {driver} board_ip={board_ip} "
                f"config=\"{config_str}\""
            )
        else:
            lines.append(f"loadrt {driver} config=\"{config_str}\"")
        lines.append("")

        # PID components
        num_axes = len(c.axis_config)
        if c.realtime.use_pid:
            lines.append(f"loadrt pid num_chan={num_axes}")

        # Optional components
        if c.realtime.use_absolute:
            lines.append("loadrt abs count=1")
        if c.realtime.use_scale:
            lines.append("loadrt scale count=2")
        if c.realtime.use_lowpass:
            lines.append("loadrt lowpass count=1")
        if c.realtime.use_mux2:
            lines.append("loadrt mux2 count=1")
        for comp in c.realtime.custom_components:
            lines.append(f"loadrt {comp}")

        # VFD
        ext = c.external
        if ext.use_serial_vfd and ext.vfd.enabled:
            lines.append(f"loadusr -Wn vfd {ext.vfd.driver}")

        lines += ["", "# ── Thread functions ────────────────────────────────────────", ""]

        lines.append("addf hm2_[HOSTMOT2](BOARD).read          servo-thread")
        lines.append("addf motion-command-handler              servo-thread")
        lines.append("addf motion-controller                   servo-thread")
        if c.realtime.use_pid:
            for i in range(num_axes):
                lines.append(f"addf pid.{i}.do-pid-calcs              servo-thread")
        if c.realtime.use_lowpass:
            lines.append("addf lowpass.0                           servo-thread")
        lines.append("addf hm2_[HOSTMOT2](BOARD).write         servo-thread")
        lines.append("")

        # ── setp — stepgen timing from axis config ─────────────────────────
        lines += ["# ── StepGen timing parameters ──────────────────────────────", ""]
        for i, ax_letter in enumerate(c.axis_config):
            ax = c.axes.get(ax_letter)
            if ax is None:
                continue
            prefix = f"hm2_[HOSTMOT2](BOARD).stepgen.{i:02d}"
            lines.append(f"setp {prefix}.step_type        0")
            lines.append(f"setp {prefix}.control-type     1")   # velocity mode
            lines.append(f"setp {prefix}.steplen          {ax.step_time}")
            lines.append(f"setp {prefix}.stepspace        {ax.step_space}")
            lines.append(f"setp {prefix}.dirhold          {ax.direction_hold}")
            lines.append(f"setp {prefix}.dirsetup         {ax.direction_setup}")
            lines.append(f"setp {prefix}.maxaccel         {ax.stepgen_maxaccel}")
            lines.append(f"setp {prefix}.maxvel           {ax.stepgen_maxvel}")
            lines.append("")

        # ── setp — PWM / watchdog ──────────────────────────────────────────
        lines += ["# ── Mesa board parameters ─────────────────────────────────", ""]
        wd_ns = int(m.watchdog_timeout * 1_000_000)
        lines.append(f"setp hm2_[HOSTMOT2](BOARD).watchdog.timeout_ns  {wd_ns}")
        lines.append(f"setp hm2_[HOSTMOT2](BOARD).pwmgen.pwm_frequency  {m.pwm_base_freq}")
        lines.append("")

        # ── PID setp ──────────────────────────────────────────────────────
        if c.realtime.use_pid:
            lines += ["# ── PID parameters ─────────────────────────────────────────", ""]
            for i, ax_letter in enumerate(c.axis_config):
                ax = c.axes.get(ax_letter)
                if ax is None:
                    continue
                p = f"pid.{i}"
                lines.append(f"setp {p}.Pgain     {ax.pid_p}")
                lines.append(f"setp {p}.Igain     {ax.pid_i}")
                lines.append(f"setp {p}.Dgain     {ax.pid_d}")
                lines.append(f"setp {p}.FF0       {ax.pid_ff0}")
                lines.append(f"setp {p}.FF1       {ax.pid_ff1}")
                lines.append(f"setp {p}.FF2       {ax.pid_ff2}")
                lines.append(f"setp {p}.bias      {ax.pid_bias}")
                lines.append(f"setp {p}.maxoutput {ax.pid_max_output}")
                lines.append("")

        # ── Axis net statements ────────────────────────────────────────────
        lines += ["# ── Axis nets ────────────────────────────────────────────────", ""]
        for i, ax_letter in enumerate(c.axis_config):
            ax = c.axes.get(ax_letter)
            if ax is None:
                continue
            j = i
            lines.append(f"# Joint {j} ({ax_letter})")
            if c.realtime.use_pid:
                lines.append(f"net j{j}pos-cmd  joint.{j}.motor-pos-cmd => pid.{j}.command")
                lines.append(f"net j{j}pos-fb   hm2_[HOSTMOT2](BOARD).encoder.{j:02d}.position => pid.{j}.feedback => joint.{j}.motor-pos-fb")
                lines.append(f"net j{j}output   pid.{j}.output => hm2_[HOSTMOT2](BOARD).stepgen.{j:02d}.velocity-cmd")
                lines.append(f"net j{j}enable   joint.{j}.amp-enable-out => pid.{j}.enable => hm2_[HOSTMOT2](BOARD).stepgen.{j:02d}.enable")
            else:
                lines.append(f"net j{j}pos-cmd  joint.{j}.motor-pos-cmd => hm2_[HOSTMOT2](BOARD).stepgen.{j:02d}.position-cmd")
                lines.append(f"net j{j}pos-fb   hm2_[HOSTMOT2](BOARD).stepgen.{j:02d}.position-fb => joint.{j}.motor-pos-fb")
                lines.append(f"net j{j}enable   joint.{j}.amp-enable-out => hm2_[HOSTMOT2](BOARD).stepgen.{j:02d}.enable")
            lines.append("")

        # ── Connector-derived nets ─────────────────────────────────────────
        lines += ["# ── Connector pin nets (from pin assignment page) ────────────", ""]
        lines += self._generate_connector_nets()
        lines.append("")

        # ── Spindle ───────────────────────────────────────────────────────
        lines += ["# ── Spindle ──────────────────────────────────────────────────", ""]
        lines.append(f"net spindle-vel-cmd  spindle.0.speed-out-rps-abs => hm2_[HOSTMOT2](BOARD).7i76.0.0.spinout")
        lines.append(f"net spindle-enable   spindle.0.on  => hm2_[HOSTMOT2](BOARD).7i76.0.0.spinena")
        lines.append(f"net spindle-ccw      spindle.0.reverse => hm2_[HOSTMOT2](BOARD).7i76.0.0.spindir")
        if c.spindle.use_encoder:
            lines.append(f"net spindle-revs     hm2_[HOSTMOT2](BOARD).encoder.{num_axes:02d}.position => spindle.0.revs")
            lines.append(f"net spindle-vel-fb   hm2_[HOSTMOT2](BOARD).encoder.{num_axes:02d}.velocity => spindle.0.speed-in")
        lines.append("")

        # ── E-stop ────────────────────────────────────────────────────────
        lines += ["# ── E-stop / Enable ─────────────────────────────────────────", ""]
        # Check if user assigned an E-Stop In pin
        estop_assigned = self._find_assigned_hal("E-Stop In")
        if estop_assigned:
            lines.append(f"net estop-in  {estop_assigned} => iocontrol.0.emc-enable-in")
        else:
            lines.append("net estop-out  iocontrol.0.user-enable-out => iocontrol.0.emc-enable-in")
        lines.append("")

        # ── Amp enable ────────────────────────────────────────────────────
        amp_assigned = self._find_assigned_hal("Amp Enable")
        if amp_assigned:
            lines += [
                "# ── Amp Enable ───────────────────────────────────────────────────",
                f"net amp-enable  motion.spindle-on => {amp_assigned}",
                "",
            ]

        # ── Charge pump ───────────────────────────────────────────────────
        cp_assigned = self._find_assigned_hal("Charge Pump")
        if cp_assigned:
            lines += [
                f"net charge-pump  charge-pump.out => {cp_assigned}",
                "",
            ]

        # ── Home / limits (from pin assignment) ───────────────────────────
        lines += self._generate_home_limit_nets()

        # ── External controls ─────────────────────────────────────────────
        ext_hal = self._generate_external_controls_hal()
        if ext_hal.strip():
            lines += [
                "",
                "# ── External Controls ═══════════════════════════════════════",
                ext_hal,
            ]

        # ── Custom HAL ────────────────────────────────────────────────────
        if c.options.custom_hal_before:
            lines += ["", "# ── Custom HAL (before) ──────────────────────────────────────",
                      c.options.custom_hal_before]
        if c.options.custom_hal_after:
            lines += ["", "# ── Custom HAL (after) ───────────────────────────────────────",
                      c.options.custom_hal_after]

        return "\n".join(lines) + "\n"

    def generate_custom_hal(self) -> str:
        return (
            "# custom.hal — Add your custom HAL commands here.\n"
            "# This file is NOT overwritten by PNCconf.\n\n"
        )

    def generate_ini(self) -> str:
        """Generate the .ini file content."""
        sections = self.cfg.to_ini_sections()
        lines: List[str] = [
            f"# Generated by PNCconf Qt Wizard",
            f"# Machine: {self.cfg.machine_name}",
            "",
        ]
        for section, kv in sections.items():
            lines.append(f"[{section}]")
            for key, val in kv.items():
                lines.append(f"{key} = {val}")
            lines.append("")
        return "\n".join(lines)

    def write_all(self, output_dir: str):
        """Write all generated files to output_dir."""
        os.makedirs(output_dir, exist_ok=True)
        name = self.cfg.machine_name

        with open(os.path.join(output_dir, f"{name}.hal"), "w") as f:
            f.write(self.generate_machine_hal())

        with open(os.path.join(output_dir, "custom.hal"), "w") as f:
            f.write(self.generate_custom_hal())

        with open(os.path.join(output_dir, f"{name}.ini"), "w") as f:
            f.write(self.generate_ini())

    # ─────────────────────────────────────────────────────────────────────────
    # Internal helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _all_assigned_pins(self):
        """Yield (function, hal_pin, invert) for every non-Unused pin."""
        for conn in self.cfg.mesa.connectors:
            for pin in conn.pins:
                if pin.function != "Unused" and pin.hal_pin:
                    yield pin.function, pin.hal_pin, pin.invert

    def _find_assigned_hal(self, function: str) -> Optional[str]:
        """Return the hal_pin string for the first pin assigned to `function`."""
        for conn in self.cfg.mesa.connectors:
            for pin in conn.pins:
                if pin.function == function:
                    return pin.hal_pin or pin.resolve_hal(self.cfg.mesa.board_name)
        return None

    def _generate_connector_nets(self) -> List[str]:
        """
        Produce 'net' statements for all connector pins that are not
        handled elsewhere (stepgens and encoders are wired in the axis
        section; spindle signals get their own section).
        """
        skip_funcs = STEPGEN_FUNCTIONS | ENCODER_FUNCTIONS | {
            "Unused", "GPIO Input", "GPIO Output",
            "E-Stop In", "Amp Enable", "Charge Pump",
            "Home X", "Home Y", "Home Z", "Home A",
            "Limit+ X", "Limit- X", "Limit+ Y", "Limit- Y",
            "Limit+ Z", "Limit- Z", "Probe In",
            "Spindle Out", "Spindle Enable", "Spindle Dir",
        }

        sig_name_map: Dict[str, str] = {
            "MPG A":    "mpg-a",
            "MPG B":    "mpg-b",
            "UART TX":  "uart-tx",
            "UART RX":  "uart-rx",
            "PWM-0 Out": "pwm-0-out",
            "PWM-0 Enable": "pwm-0-enable",
            "PWM-1 Out": "pwm-1-out",
            "PWM-1 Enable": "pwm-1-enable",
        }

        lines = []
        for func, hal_pin, invert in self._all_assigned_pins():
            if func in skip_funcs:
                continue
            if func.startswith("SSerial"):
                continue
            sig = sig_name_map.get(func, func.lower().replace(" ", "-").replace("/", "-"))
            inv_str = ""
            if invert:
                # For GPIO outputs, set the invert setp
                lines.append(f"setp {hal_pin}.invert  1")
            direction = "=>" if "out" in hal_pin.lower() or "Out" in func else "<="
            lines.append(f"net {sig}  {direction} {hal_pin}")

        return lines

    def _generate_home_limit_nets(self) -> List[str]:
        """Wire home and limit switch signals to joint pins."""
        sig_to_joint: Dict[str, str] = {}
        for i, ax in enumerate(self.cfg.axis_config):
            sig_to_joint[f"Home {ax}"]    = f"joint.{i}.home-sw-in"
            sig_to_joint[f"Limit+ {ax}"]  = f"joint.{i}.pos-lim-sw-in"
            sig_to_joint[f"Limit- {ax}"]  = f"joint.{i}.neg-lim-sw-in"
        sig_to_joint["Probe In"] = "motion.probe-input"

        lines = []
        found_any = False
        for func, hal_pin, invert in self._all_assigned_pins():
            if func not in sig_to_joint:
                continue
            if not found_any:
                lines.append("# ── Home / Limit switches ────────────────────────────────────")
                found_any = True
            joint_pin = sig_to_joint[func]
            sig_name  = func.lower().replace(" ", "-").replace("+", "pos").replace("-", "neg")
            if invert:
                lines.append(f"setp {hal_pin}-not  1")
            lines.append(f"net {sig_name}  {hal_pin} => {joint_pin}")

        if found_any:
            lines.append("")
        return lines

    def _generate_external_controls_hal(self) -> str:
        """Generate HAL snippet for all enabled external controls."""
        try:
            from hal_generator.ext_controls_hal import ExternalControlsHAL
            ext_gen = ExternalControlsHAL(
                ext=self.cfg.external,
                machine_name=self.cfg.machine_name,
                axis_config=self.cfg.axis_config,
            )
            return ext_gen.generate_all()
        except Exception:
            return ""
