"""
INI File Generator
==================
Generates LinuxCNC INI files from MachineConfig.
"""

from __future__ import annotations
import os
from config.machine_config import MachineConfig, AxisConfig


class INIGenerator:
    def __init__(self, cfg: MachineConfig):
        self.cfg = cfg

    def generate(self) -> str:
        c = self.cfg
        name = c.machine_name
        lines = [
            f"# Generated by PNCconf Qt Wizard",
            f"# Machine: {name}",
            "",
        ]

        # ── EMC ──────────────────────────────────────────────────────────────
        lines += [
            "[EMC]",
            f"MACHINE = {name}",
            "DEBUG = 0",
            "",
        ]

        # ── DISPLAY ──────────────────────────────────────────────────────────
        lines += [
            "[DISPLAY]",
            f"DISPLAY = {c.screen.gui_type}",
            f"POSITION_OFFSET = {c.screen.position_offset.upper()}",
            f"GEOMETRY = {c.screen.geometry}",
            f"MAX_FEED_OVERRIDE = {c.screen.max_feed_override:.2f}",
            f"MAX_SPINDLE_OVERRIDE = {c.screen.max_spindle_override:.2f}",
            f"EDITOR = {c.screen.editor}",
            f"INCREMENTS = {c.screen.increments}",
            "",
        ]

        # ── FILTER ───────────────────────────────────────────────────────────
        lines += [
            "[FILTER]",
            "PROGRAM_EXTENSION = .ngc,.nc,.g G-Code File",
            "",
        ]

        # ── RS274NGC ─────────────────────────────────────────────────────────
        lines += [
            "[RS274NGC]",
            "PARAMETER_FILE = linuxcnc.var",
            "",
        ]

        # ── EMCMOT ───────────────────────────────────────────────────────────
        lines += [
            "[EMCMOT]",
            "EMCMOT = motmod",
            f"COMM_TIMEOUT = 1.0",
            f"SERVO_PERIOD = {c.servo_period_ns}",
            "",
        ]

        # ── HOSTMOT2 ─────────────────────────────────────────────────────────
        lines += [
            "[HOSTMOT2]",
            f"DRIVER = hm2_eth",
            f"BOARD = {c.mesa.board_name}",
            f"FIRMWARE = {c.mesa.firmware}",
            "",
        ]

        # ── TASK ─────────────────────────────────────────────────────────────
        lines += [
            "[TASK]",
            "TASK = milltask",
            "CYCLE_TIME = 0.010",
            "",
        ]

        # ── HAL ──────────────────────────────────────────────────────────────
        lines += [
            "[HAL]",
            f"HALFILE = {name}.hal",
            "HALFILE = custom.hal",
            "",
        ]

        # ── HALUI ────────────────────────────────────────────────────────────
        if c.options.num_halui_commands > 0:
            lines.append("[HALUI]")
            for cmd in c.options.halui_commands:
                lines.append(f"MDI_COMMAND = {cmd}")
            lines.append("")

        # ── TRAJ ─────────────────────────────────────────────────────────────
        unit_str = "mm" if c.units == "metric" else "inch"
        lines += [
            "[TRAJ]",
            f"AXES = {len(c.axis_config)}",
            f"COORDINATES = {' '.join(c.axis_config)}",
            f"LINEAR_UNITS = {unit_str}",
            "ANGULAR_UNITS = degree",
            f"MAX_LINEAR_VELOCITY = {max((c.axes[a].max_velocity for a in c.axis_config if a in c.axes), default=50):.3f}",
            f"MAX_LINEAR_ACCELERATION = {max((c.axes[a].max_acceleration for a in c.axis_config if a in c.axes), default=500):.3f}",
            "",
        ]

        # ── KINS ─────────────────────────────────────────────────────────────
        num_joints = len(c.axis_config)
        lines += [
            "[KINS]",
            "KINEMATICS = trivkins",
            f"JOINTS = {num_joints}",
            "",
        ]

        # ── Per-axis JOINT sections ────────────────────────────────────────
        for i, ax_letter in enumerate(c.axis_config):
            ax: AxisConfig = c.axes.get(ax_letter, AxisConfig(name=ax_letter))
            lines += self._joint_section(i, ax_letter, ax, c.units)

        # ── SPINDLE ──────────────────────────────────────────────────────────
        sp = c.spindle
        lines += [
            "[SPINDLE_9]",
            f"MAX_FORWARD_VELOCITY = {sp.max_rpm:.1f}",
            f"MAX_REVERSE_VELOCITY = {sp.max_rpm:.1f}",
            f"HOME_SEARCH_VEL = 0",
            "",
        ]

        # ── ClassicLadder ────────────────────────────────────────────────────
        if c.options.use_classicladder:
            lines += [
                "[CLASSICLADDER]",
                f"LADDER_PROGRAM = {c.options.classicladder_program}",
                "",
            ]

        return "\n".join(lines)

    def _joint_section(self, idx: int, letter: str, ax: AxisConfig, units: str) -> list:
        u = "mm" if units == "metric" else "in"
        return [
            f"[JOINT_{idx}]",
            f"TYPE = LINEAR",
            f"MAX_VELOCITY = {ax.max_velocity:.3f}",
            f"MAX_ACCELERATION = {ax.max_acceleration:.3f}",
            f"STEPGEN_MAXVEL = {ax.stepgen_maxvel:.3f}",
            f"STEPGEN_MAXACCEL = {ax.stepgen_maxaccel:.3f}",
            f"SCALE = {ax.scale:.4f}",
            f"FERROR = {ax.ferror:.3f}",
            f"MIN_FERROR = {ax.min_ferror:.3f}",
            f"MIN_LIMIT = {-ax.travel:.3f}",
            f"MAX_LIMIT = {ax.travel:.3f}",
            f"HOME = {ax.home_position:.3f}",
            f"HOME_OFFSET = {ax.home_switch_location:.3f}",
            f"HOME_SEARCH_VEL = {ax.search_velocity:.3f}",
            f"HOME_LATCH_VEL = {ax.latch_velocity:.3f}",
            f"HOME_FINAL_VEL = 0",
            f"HOME_USE_INDEX = NO",
            f"HOME_IGNORE_LIMITS = YES",
            f"HOME_SEQUENCE = {ax.home_sequence}",
            f"# PID: P={ax.pid_p} I={ax.pid_i} D={ax.pid_d}",
            "",
        ]

    def write(self, output_dir: str):
        os.makedirs(output_dir, exist_ok=True)
        path = os.path.join(output_dir, f"{self.cfg.machine_name}.ini")
        with open(path, "w") as f:
            f.write(self.generate())
        return path
